set nocompatible              " be iMproved, required
filetype off                  " required

let $VIM_PLUGINS = 'HOMESED/.vimrc-plugins'
if filereadable(expand($VIM_PLUGINS))
  source $VIM_PLUGINS
else
    " Fallback to just static-darcula theme
    let $VIM_COLORSCHEME = "HOMESED/.vim/colors/darcula.vim"
    if filereadable(expand($VIM_COLORSCHEME))
        colorscheme darcula

        " Fix for mac default terminal
        if $TERM isnot# 'xterm-256color'
            set termguicolors
        endif
    endif
endif

set incsearch
set hlsearch

set wildmenu
set wildmode=longest:full,full
set noswapfile

" Some indentation rules
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set shiftround
set smarttab
set autoindent
set smartindent
set invnumber
set wrap

set mouse=a
set splitbelow
set splitright
set autoread

syntax on

" Move paste toggle to Ctrl + B
set pastetoggle=<C-b>

" Undo
map <C-z> u
imap <C-z> <ESC>ui
" Redo
imap <C-r> <ESC><C-r>i

" move between buffers.
" the default is C-W + hljk or left down up right
noremap <A-Up> <C-w><Up>
imap <A-Up> <ESC><A-Up>i
noremap <A-Down> <C-w><Down>
imap <A-Down> <ESC><A-Down>i
noremap <A-Left> <C-w><Left>
imap <A-Left> <ESC><A-Left>i
noremap <A-Right> <C-w><Right>
imap <A-Right> <ESC><A-Right>i

" Build for c/cpp
autocmd FileType c setlocal makeprg=time\ gcc\ -g\ -O2\ -Wall\ %\ -o\ _%<\ -lm
autocmd FileType cpp setlocal makeprg=time\ c++\ -std=c++14\ -O2\ -Wall\ %\ -o\ _%<\ -lm

autocmd FileType c,cpp map <C-b> :!clear<CR>:make!<CR>
autocmd FileType c,cpp imap <C-b> <ESC><C-b>

imap <C-r> <ESC><C-r>

" Running C/ C++
autocmd FileType c,cpp map <C-r> :!clear<CR>:make!<cr>:!time ./_%< <CR>
" Running Python
autocmd FileType python map <C-r> :!clear<CR>:!time python3 % <CR>
" Running Bash
autocmd FileType bash,sh map <C-r> :!clear<CR>:!time ./% <CR>

" Move faster
 map <C-Up> <Up><Up><Up><Up><Up><Up><Up><Up><Up><Up>
 map <C-Down> <Down><Down><Down><Down><Down><Down><Down><Down><Down><Down>
 map <C-Left> <Left><Left><Left><Left><Left><Left><Left><Left><Left><Left>
 map <C-Right> <Right><Right><Right><Right><Right><Right><Right><Right><Right><Right>
imap <C-Up> <Up><Up><Up><Up><Up><Up><Up><Up><Up><Up>
imap <C-Down> <Down><Down><Down><Down><Down><Down><Down><Down><Down><Down>
imap <C-Left> <Left><Left><Left><Left><Left><Left><Left><Left><Left><Left>
imap <C-Right> <Right><Right><Right><Right><Right><Right><Right><Right><Right><Right>

" Evil osx shortcuts. There is no home/end/pageup/pagedown.
" terminal -> config -> keyboard -> bind any keys to generate
" alt + hjlk in order left, up, right, down
 map ˙ <Left><Left><Left><Left><Left><Left><Left><Left><Left><Left>
 map ∆ <Up><Up><Up><Up><Up><Up><Up><Up><Up><Up>
 map ˚ <Right><Right><Right><Right><Right><Right><Right><Right><Right><Right>
 map ¬ <Down><Down><Down><Down><Down><Down><Down><Down><Down><Down>
imap ˙ <Left><Left><Left><Left><Left><Left><Left><Left><Left><Left>
imap ∆ <Up><Up><Up><Up><Up><Up><Up><Up><Up><Up>
imap ˚ <Right><Right><Right><Right><Right><Right><Right><Right><Right><Right>
imap ¬ <Down><Down><Down><Down><Down><Down><Down><Down><Down><Down>
